version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-service
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama # Persist models in a named volume
    networks:
      - chat-network
    deploy:
       resources:
         reservations:
           devices:
             - driver: nvidia
               count: 1 # or 'all'
               capabilities: [gpu]

  backend:
    build:
      context: ./backend/chat-backend
      dockerfile: Dockerfile
    container_name: chat-backend-container
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_API_URL=http://ollama:11434
      - OLLAMA_MODEL=phi3
    depends_on:
      - ollama
    networks:
      - chat-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chat-frontend-container
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - chat-network

volumes:
  ollama_data:

networks:
  chat-network:
    driver: bridge